### ISSUE TITLE
如何传递变量到模板?

### ISSUE THREAD

**Issue by tlijian1989** [zjango/sendcloud#2]
邮件模板需要提前在sendcloud 定义,所以我用 (string)view::make 生成的内容,无法发送,能不能定义模板名,然后传参数呢?  
比如我的模板是 : 欢迎%name%注册,点击地址激活 %url%

**Comment by zjango** [comment]
模板是sendcloud的限制, 需要经过sendcloud的审核

**Comment by zjango** [comment]
另外, 传递变量到模板跟正常的view一致
